// <auto-generated />
using System;
using System.Collections.Generic;
using BackendSource.DataBaseSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendSource.Migrations
{
    [DbContext(typeof(DbContextBa))]
    [Migration("20260511170628_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendSource.DataBaseSystem.GamesAndCodes.GameVersionTable", b =>
                {
                    b.Property<Guid>("GameVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdateDesc")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hashFromVersion")
                        .HasColumnType("text");

                    b.HasKey("GameVersionId");

                    b.HasIndex("GameId");

                    b.ToTable("GameVersions");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.GamesAndCodes.GamesKeys", b =>
                {
                    b.Property<Guid>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("KeyId");

                    b.ToTable("GamesKeys");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.GamesAndCodes.GamesTable", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GameIsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("GameItsFree")
                        .HasColumnType("boolean");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.GamesAndCodes.LicencesTable", b =>
                {
                    b.Property<Guid>("LicenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevokedReason")
                        .HasColumnType("integer");

                    b.HasKey("LicenceId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.ToTable("LicencesTable");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.JwtAndRefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasMaxLength(255)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Expired");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("Revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.ToTable("refreshTable");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.Programers.TeamProgramingDatabse", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("GameId")
                        .HasColumnType("uuid[]");

                    b.Property<bool>("ItsRevoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RevokedReason")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("teamTable");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.RoleTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.Roles_Permissions.PermissionsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PermissionsTables");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.Roles_Permissions.RolePermissionTable", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissionTable");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.UserTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ItsBanned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamProgramingDatabseTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamProgramingDatabseTeamId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.GamesAndCodes.GameVersionTable", b =>
                {
                    b.HasOne("BackendSource.DataBaseSystem.GamesAndCodes.GamesTable", "Game")
                        .WithMany("GameVersions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.GamesAndCodes.LicencesTable", b =>
                {
                    b.HasOne("BackendSource.DataBaseSystem.GamesAndCodes.GamesTable", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSource.DataBaseSystem.UserTable", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.Roles_Permissions.RolePermissionTable", b =>
                {
                    b.HasOne("BackendSource.DataBaseSystem.Roles_Permissions.PermissionsTable", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSource.DataBaseSystem.RoleTable", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.UserTable", b =>
                {
                    b.HasOne("BackendSource.DataBaseSystem.RoleTable", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSource.DataBaseSystem.Programers.TeamProgramingDatabse", null)
                        .WithMany("UsersInTeam")
                        .HasForeignKey("TeamProgramingDatabseTeamId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.GamesAndCodes.GamesTable", b =>
                {
                    b.Navigation("GameVersions");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.Programers.TeamProgramingDatabse", b =>
                {
                    b.Navigation("UsersInTeam");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.RoleTable", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BackendSource.DataBaseSystem.Roles_Permissions.PermissionsTable", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
